// Code generated by protoc-gen-go.
// source: pb3null.proto
// DO NOT EDIT!

/*
Package pb3null is a generated protocol buffer package.

It is generated from these files:
	pb3null.proto

It has these top-level messages:
	NullInt64
	NullString
*/
package pb3null

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NullInt64 struct {
	Int64 int64 `protobuf:"varint,1,opt,name=int64" json:"int64,omitempty"`
	Valid bool  `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *NullInt64) Reset()                    { *m = NullInt64{} }
func (m *NullInt64) String() string            { return proto.CompactTextString(m) }
func (*NullInt64) ProtoMessage()               {}
func (*NullInt64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NullInt64) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *NullInt64) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type NullString struct {
	String_ string `protobuf:"bytes,1,opt,name=string" json:"string,omitempty"`
	Valid   bool   `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
}

func (m *NullString) Reset()                    { *m = NullString{} }
func (m *NullString) String() string            { return proto.CompactTextString(m) }
func (*NullString) ProtoMessage()               {}
func (*NullString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NullString) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *NullString) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*NullInt64)(nil), "pb3null.NullInt64")
	proto.RegisterType((*NullString)(nil), "pb3null.NullString")
}

func init() { proto.RegisterFile("pb3null.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0x32, 0xce,
	0x2b, 0xcd, 0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xcc, 0xb9,
	0x38, 0xfd, 0x4a, 0x73, 0x72, 0x3c, 0xf3, 0x4a, 0xcc, 0x4c, 0x84, 0x44, 0xb8, 0x58, 0x33, 0x41,
	0x0c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x08, 0x07, 0x24, 0x5a, 0x96, 0x98, 0x93, 0x99,
	0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x11, 0x04, 0xe1, 0x28, 0x59, 0x71, 0x71, 0x81, 0x34, 0x06,
	0x97, 0x14, 0x65, 0xe6, 0xa5, 0x0b, 0x89, 0x71, 0xb1, 0x15, 0x83, 0x59, 0x60, 0xad, 0x9c, 0x41,
	0x50, 0x1e, 0x76, 0xbd, 0x4e, 0x9c, 0x51, 0x30, 0xfb, 0x93, 0xd8, 0xc0, 0xee, 0x31, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xb9, 0x04, 0x66, 0x18, 0xa0, 0x00, 0x00, 0x00,
}
